/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        "getting-started/introduction", 
        "getting-started/installation", 
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [ 
        "tutorials/admin-settings/overview/authentication-permissions-and-configuration",
        "tutorials/admin-settings/overview/authentication/active-directory/configuring-active-directory",
        "tutorials/admin-settings/overview/authentication/azure-ad/configuring-azure-ad",
        "tutorials/admin-settings/overview/authentication/freeipa/configuring-freeipa",
        "tutorials/admin-settings/overview/authentication/github/configuring-github",
        "tutorials/admin-settings/overview/authentication/google-oauth/configuring-google-oauth",
        "tutorials/admin-settings/overview/authentication/keycloak-oidc/configuring-keycloak-oidc",
        "tutorials/admin-settings/overview/authentication/keycloak-saml/configuring-keycloak-saml",
        "tutorials/admin-settings/overview/authentication/local/local-authentication",
        "tutorials/admin-settings/overview/authentication/microsoft-adfs/configuring-ms-adfs-for-rancher",
        "tutorials/admin-settings/overview/authentication/microsoft-adfs/configuring-rancher-for-ms-adfs",
        "tutorials/admin-settings/overview/authentication/microsoft-adfs/microsoft-adfs-overview",
        "tutorials/admin-settings/overview/authentication/okta-saml/configuring-okta-saml",
        "tutorials/admin-settings/overview/authentication/open-ldap/configuring-openldap",
        "tutorials/admin-settings/overview/authentication/open-ldap/openldap-config-reference",
        "tutorials/admin-settings/overview/authentication/ping-federate/configuring-pingidentity-saml",
        "tutorials/admin-settings/overview/authentication/shibboleth/configuring-shibboleth",
        "tutorials/admin-settings/overview/authentication/shibboleth/shibboleth-and-openldap-permissions",
        "tutorials/admin-settings/overview/authentication/users-and-groups/users-and-groups",
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'How-to Guides',
      items: [
        "how-to-guides/hello-world-example",
        "how-to-guides/create-multi-node-cluster",
        "how-to-guides/setup-NGINX-Ingress-Controller",
        "how-to-guides/vs-code-docker", 
        "how-to-guides/vs-code-remote-containers", 
        "how-to-guides/rancher-on-rancher-desktop",
        "how-to-guides/skaffold-and-rancher-desktop",
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'References',
      items: [
        "references/architecture",
        "references/rdctl-command-reference"
      ],
      collapsed: true,
    },
    "faq"
  ],   
};

module.exports = sidebars;
