/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [ 
        {
          type: 'category',
          label: 'Introduction',
          items: [
            "getting-started/introduction/rancher-manager",
            "getting-started/introduction/overview",
            "getting-started/introduction/docs-structure",
                 ], 
            collapsed: true,          
        },
        {
          type: 'category',
          label: 'Quick Start Guides',
          items: [
            {
              type: 'category',
              label: 'Deploy Rancher Manager',
              items: [
                    "getting-started/quick-start-guides/deploy-rancher-manager/aws-with-terraform",
                    "getting-started/quick-start-guides/deploy-rancher-manager/aws-with-eks",
                    "getting-started/quick-start-guides/deploy-rancher-manager/azure",
                    "getting-started/quick-start-guides/deploy-rancher-manager/digitalocean",
                    "getting-started/quick-start-guides/deploy-rancher-manager/gcp",
                    "getting-started/quick-start-guides/deploy-rancher-manager/hetzner-cloud",
                    "getting-started/quick-start-guides/deploy-rancher-manager/vagrant",
                    "getting-started/quick-start-guides/deploy-rancher-manager/equinix-metal",
                    "getting-started/quick-start-guides/deploy-rancher-manager/helm-cli",
                     ]
            },
            {
              type: 'category',
              label: 'Deploy Rancher Workloads',
              items: [      
                    "getting-started/quick-start-guides/deploy-workloads/workload-ingress",
                    "getting-started/quick-start-guides/deploy-workloads/nodeports",
                           ],
                           collapsed: true,
                  }
                     ]
        },
        {
          type: 'category',
          label: 'Installation and Upgrade',
          items: [
            {
              type: 'category',
              label: 'Installation Requirements',
              items: [
                    "getting-started/installation-and-upgrade/installation-requirements/install-docker",
                    "getting-started/installation-and-upgrade/installation-requirements/dockershim",
                    "getting-started/installation-and-upgrade/installation-requirements/port-requirements",
                     ],
                collapsed: true,
            },
            {
              type: 'category',
              label: 'Install/Upgrade on a Kubernetes Cluster',
              items: [      
                    "getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/helm-chart-options",
                    "getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rollbacks",
                    "getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/upgrades",
                    "getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/air-gapped-upgrades",
                    "getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-amazon-eks",
                    "getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-aks",
                    "getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-gke",
                    "getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/troubleshooting",
                    ],
                  collapsed: true,
            },
            {
              type: 'category',
              label: 'Other Installation Methods',
              items: [      
                  {
                    type: 'category',
                    label: 'Air-Gapped Helm CLI Install',
                    items: [
                          "getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/infrastructure-private-registry",
                          "getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/publish-images",
                          "getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/install-kubernetes",
                          "getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/rancher-ha",    
                           ]
                  },
                  {
                    type: 'category',
                    label: 'Rancher on a Single Node with Docker',
                    items: [
                          "getting-started/installation-and-upgrade/other-installation-methods/rancher-on-a-single-node-with-docker/http-proxy-configuration",
                          "getting-started/installation-and-upgrade/other-installation-methods/rancher-on-a-single-node-with-docker/upgrade-docker-installed-rancher",
                          "getting-started/installation-and-upgrade/other-installation-methods/rancher-on-a-single-node-with-docker/roll-back-docker-installed-rancher",
                          "getting-started/installation-and-upgrade/other-installation-methods/rancher-on-a-single-node-with-docker/advanced-options",
                          "getting-started/installation-and-upgrade/other-installation-methods/rancher-on-a-single-node-with-docker/certificate-troubleshooting",
                           ]
                  },
                  { 
                    type: 'category',
                    label: 'Rancher Behind an HTTP Proxy',
                    items: [ 
                          "getting-started/installation-and-upgrade/other-installation-methods/rancher-behind-an-http-proxy/set-up-infrastructure",
                          "getting-started/installation-and-upgrade/other-installation-methods/rancher-behind-an-http-proxy/install-kubernetes",
                          "getting-started/installation-and-upgrade/other-installation-methods/rancher-behind-an-http-proxy/install-rancher",
                           ]
                          }
                        ],
                        collapsed: true, 
            },
            {
              type: 'category',
              label: 'Resources',
              items: [
                    "getting-started/installation-and-upgrade/resources/choose-a-rancher-version",
                    "getting-started/installation-and-upgrade/resources/helm-version-requirements",
                    "getting-started/installation-and-upgrade/resources/add-tls-secrets",
                    "getting-started/installation-and-upgrade/resources/tls-settings",
                    "getting-started/installation-and-upgrade/resources/custom-ca-root-certificates",
                    "getting-started/installation-and-upgrade/resources/upgrade-cert-manager",
                    "getting-started/installation-and-upgrade/resources/update-private-ca-certificate",
                    "getting-started/installation-and-upgrade/resources/bootstrap-password",
                     ]
            }, 
            {
              type: 'category',
              label: 'Upgrade and Roll Back Kubernetes',
              items: [
                    "getting-started/installation-and-upgrade/upgrade-and-roll-back-kubernetes/upgrade-and-roll-back",
                     ]
            },
            {
              type: 'category',
              label: 'Upgrade Kubernetes without Upgrading Rancher',
              items: [
                    "getting-started/installation-and-upgrade/upgrade-kubernetes-without-upgrading-rancher/upgrade-kubernetes-not-rancher",
                     ],
                  collapsed: true,
            },
            { 
              type: 'category',
              label: 'Advanced Options',
              items: [
                {
                    type: 'category',
                    label: 'Enable Experimental Features',
                    items: [
                          "getting-started/installation-and-upgrade/advanced-options/enable-experimental-features/rancher-on-arm64",
                          "getting-started/installation-and-upgrade/advanced-options/enable-experimental-features/feature-flags",
                          "getting-started/installation-and-upgrade/advanced-options/enable-experimental-features/unsupported-storage-drivers",
                          "getting-started/installation-and-upgrade/advanced-options/enable-experimental-features/istio-traffic-management-features",
                          "getting-started/installation-and-upgrade/advanced-options/enable-experimental-features/continuous-delivery",
                           ]
                },
                {
                    type: 'category',
                    label: 'Advanced Use Cases',
                    items: [
                          "getting-started/installation-and-upgrade/advanced-options/advanced-use-cases/open-ports-with-firewalld",
                          "getting-started/installation-and-upgrade/advanced-options/advanced-use-cases/tune-etcd-for-large-installs",
                          "getting-started/installation-and-upgrade/advanced-options/advanced-use-cases/enable-api-audit-log",
                          "getting-started/installation-and-upgrade/advanced-options/advanced-use-cases/configure-layer-7-nginx-load-balancer",
                           ],
                           collapsed: true,
                          }
                        ]
            }
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [ 
        {
          type: 'category',
          label: 'Best Practices',
          items: [
            {
              type: 'category',
              label: 'Rancher Server',
              items: [
                     "tutorials/best-practices/rancher-server/on-premises-rancher-in-vsphere",
                     "tutorials/best-practices/rancher-server/rancher-deployment-strategy",
                     "tutorials/best-practices/rancher-server/tips-for-running-rancher"                            
                     ]
                    },
            {
              type: 'category',
              label: 'Rancher-Managed Clusters',
              items: [
                     "tutorials/best-practices/rancher-managed-clusters/logging-best-practices",
                     "tutorials/best-practices/rancher-managed-clusters/monitoring-best-practices",
                     "tutorials/best-practices/rancher-managed-clusters/tips-to-set-up-containers",
                     "tutorials/best-practices/rancher-managed-clusters/rancher-managed-clusters-in-vsphere"
                     ]
                    }
                  ]
        },
        {
          type: 'category',
          label: 'Kubernetes Cluster Setup',
          items: [
                  "tutorials/kubernetes-cluster-setup/high-availability-installs",
                  "tutorials/kubernetes-cluster-setup/k3s-for-rancher",
                  "tutorials/kubernetes-cluster-setup/rke1-for-rancher",
                  "tutorials/kubernetes-cluster-setup/rke2-for-rancher",
                  ],
        },
        {
          type: 'category',
          label: 'Infrastructure Setup',
          items: [
                  "tutorials/infrastructure-setup/ha-k3s-kubernetes-cluster",
                  "tutorials/infrastructure-setup/ha-rke1-kubernetes-cluster",
                  "tutorials/infrastructure-setup/ha-rke2-kubernetes-cluster",
                  "tutorials/infrastructure-setup/nodes-in-amazon-ec2",
                  "tutorials/infrastructure-setup/mysql-database-in-amazon-rds",
                  "tutorials/infrastructure-setup/nginx-load-balancer",
                  "tutorials/infrastructure-setup/amazon-elb-load-balancer",
                  ],
        },
        {
          type: 'category',
          label: 'Kubernetes Clusters in Rancher Setup',
          items: [
                {
                  type: 'category',
                  label: 'Node Requirements for Rancher-Managed Clusters',
                  items: [
                       "tutorials/kubernetes-clusters-in-rancher-setup/node-requirements-for-rancher-managed-clusters/node-requirements",
                         ],
                },
                {
                  type: 'category',
                  label: 'Checklist for Production-Ready Clusters',
                  items: [
                       "tutorials/kubernetes-clusters-in-rancher-setup/checklist-for-production-ready-clusters/recommended-cluster-architecture",
                       "tutorials/kubernetes-clusters-in-rancher-setup/checklist-for-production-ready-clusters/roles-for-nodes-in-kubernetes",
                         ],
                }
      ]
    }
  ]
       },
    {
      type: 'category',
      label: 'How-to Guides',
      items: [
        "how-to-guides/api",
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'References',
      items: [
        "references/architecture",
        "references/architecture-recommendations",
        "references/kubernetes-concepts",
      ],
      collapsed: true,
    }
  ]
}
module.exports = sidebars;
