/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
   
      'rancher-manager',             
    {    
      type: 'category',
      label: 'Getting Started', 
      items: [
        {
          type: 'category',
          label: 'Introduction',
          link: {
            type: 'doc',
            id: "introduction",
          },
          items: [
            "getting-started/introduction/overview",
            "getting-started/introduction/what-are-divio-docs",
                 ], 
        },
        {
          type: 'category',
          label: 'Quick Start Guides',
          link: {
            type: 'doc',
            id: "quick-start-guides",
          },
          items: [
            {
              type: 'category',
              label: 'Deploy Rancher Manager',
              link: {
                type: 'doc',
                id: "deploy-rancher-manager",
             },
              items: [
                    "getting-started/quick-start-guides/deploy-rancher-manager/aws-with-terraform",
                    "getting-started/quick-start-guides/deploy-rancher-manager/aws-with-eks",
                    "getting-started/quick-start-guides/deploy-rancher-manager/azure",
                    "getting-started/quick-start-guides/deploy-rancher-manager/digitalocean",
                    "getting-started/quick-start-guides/deploy-rancher-manager/gcp",
                    "getting-started/quick-start-guides/deploy-rancher-manager/hetzner-cloud",
                    "getting-started/quick-start-guides/deploy-rancher-manager/vagrant",
                    "getting-started/quick-start-guides/deploy-rancher-manager/equinix-metal",
                    "getting-started/quick-start-guides/deploy-rancher-manager/helm-cli",
              ]
            },
            {
              type: 'category',
              label: 'Deploy Rancher Workloads',
              link: {
                type: 'doc',
                id: "deploy-rancher-workloads",
              },
              items: [      
                    "getting-started/quick-start-guides/deploy-workloads/workload-ingress",
                    "getting-started/quick-start-guides/deploy-workloads/nodeports",
                     ],
                  }
              ]
        },
        {
          type: 'category',
          label: 'Installation and Upgrade',
          link: {
            type: 'doc',
            id: "installation-and-upgrade",
            },
            items: [
            {
              type: 'category',
              label: 'Installation Requirements',
              link: {
                type: 'doc',
                id: "installation-requirements",
              },
              items: [
                    "getting-started/installation-and-upgrade/installation-requirements/install-docker",
                    "getting-started/installation-and-upgrade/installation-requirements/dockershim",
                    "getting-started/installation-and-upgrade/installation-requirements/port-requirements",
                     ]
            },
            {
              type: 'category',
              label: 'Install/Upgrade on a Kubernetes Cluster',
              link: {
                type: 'doc',
                id: "install-upgrade-on-a-kubernetes-cluster",
              },
              items: [      
                    "getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rollbacks",
                    "getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/upgrades",
                    "getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/air-gapped-upgrades",
                    "getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-amazon-eks",
                    "getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-aks",
                    "getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-gke",
                    "getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/troubleshooting",
                    ]
                  }
                ]
            },
            {
              type: 'category',
              label: 'Other Installation Methods',
              link: {
                type: 'doc',
                id: "other-installation-methods",
              },
              items: [      
                  {
                    type: 'category',
                    label: 'Air-Gapped Helm CLI Install',
                    link: {
                      type: 'doc',
                      id: 'air-gapped-helm-cli-install',
                    },
                    items: [
                          "getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/infrastructure-private-registry",
                          "getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/publish-images",
                          "getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/install-kubernetes",
                          "getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/rancher-ha",    
                           ]
                  },
                  {
                    type: 'category',
                    label: 'Rancher on a Single Node with Docker',
                    link: {
                      type: 'doc',
                      id: 'rancher-on-a-single-node-with-docker',
                    },
                    items: [
                          "getting-started/installation-and-upgrade/other-installation-methods/rancher-on-a-single-node-with-docker/upgrade-docker-installed-rancher",
                          "getting-started/installation-and-upgrade/other-installation-methods/rancher-on-a-single-node-with-docker/roll-back-docker-installed-rancher",
                          "getting-started/installation-and-upgrade/other-installation-methods/rancher-on-a-single-node-with-docker/certificate-troubleshooting",
                           ]
                  },
                  { 
                    type: 'category',
                    label: 'Rancher Behind an HTTP Proxy',
                    link: {
                      type: 'doc',
                      id: 'rancher-behind-an-http-proxy',
                    },
                    items: [ 
                          "getting-started/installation-and-upgrade/other-installation-methods/rancher-behind-an-http-proxy/set-up-infrastructure",
                          "getting-started/installation-and-upgrade/other-installation-methods/rancher-behind-an-http-proxy/install-kubernetes",
                          "getting-started/installation-and-upgrade/other-installation-methods/rancher-behind-an-http-proxy/install-rancher",
                           ]
                  }
                ],
            },
            {
              type: 'category',
              label: 'Resources',
              link: {
                type: 'doc',
                id: 'resources',
              },
              items: [
                    "getting-started/installation-and-upgrade/resources/choose-a-rancher-version",
                    "getting-started/installation-and-upgrade/resources/helm-version-requirements",
                    "getting-started/installation-and-upgrade/resources/add-tls-secrets",
                    "getting-started/installation-and-upgrade/resources/custom-ca-root-certificates",
                    "getting-started/installation-and-upgrade/resources/upgrade-cert-manager",
                    "getting-started/installation-and-upgrade/resources/update-private-ca-certificate",
                    "getting-started/installation-and-upgrade/resources/bootstrap-password",
                     ]
            }, 
                    "getting-started/installation-and-upgrade/upgrade-and-roll-back-kubernetes",
                    
                    "getting-started/installation-and-upgrade/upgrade-kubernetes-without-upgrading-rancher",
            { 
              type: 'category',
              label: 'Advanced Options',
              link: {
                type: 'doc',
                id: 'advanced-options',
              },
              items: [
                {
                    type: 'category',
                    label: 'Enable Experimental Features',
                    link: {
                      type: 'doc',
                      id: 'enable-experimental-features',
                    },
                    items: [
                          "getting-started/installation-and-upgrade/advanced-options/enable-experimental-features/rancher-on-arm64",
                          "getting-started/installation-and-upgrade/advanced-options/enable-experimental-features/unsupported-storage-drivers",
                          "getting-started/installation-and-upgrade/advanced-options/enable-experimental-features/istio-traffic-management-features",
                          "getting-started/installation-and-upgrade/advanced-options/enable-experimental-features/continuous-delivery",
                           ]
                 }
                    ]
            },
            {
                    type: 'category',
                    label: 'Advanced Use Cases',
                    items: [
                          "getting-started/installation-and-upgrade/advanced-options/advanced-use-cases/open-ports-with-firewalld",
                          "getting-started/installation-and-upgrade/advanced-options/advanced-use-cases/tune-etcd-for-large-installs",
                          "getting-started/installation-and-upgrade/advanced-options/advanced-use-cases/enable-api-audit-log",
                          "getting-started/installation-and-upgrade/advanced-options/advanced-use-cases/configure-layer-7-nginx-load-balancer",
                           ]
            }
          ]
    },            
    {
      type: 'category',
      label: 'Tutorials',
      link: {
        type: 'doc',
        id: "tutorials",
      },
      items: [ 
        {
          type: 'category',
          label: 'Best Practices',
          link: {
            type: 'doc',
            id: "best-practices",
          },
          items: [
            {
              type: 'category',
              label: 'Rancher Server',
              link: {
                type: 'doc',
                id: "rancher-server",
              },
              items: [
                     "tutorials/best-practices/rancher-server/on-premises-rancher-in-vsphere",
                     "tutorials/best-practices/rancher-server/rancher-deployment-strategy",
                     "tutorials/best-practices/rancher-server/tips-for-running-rancher"                            
                     ]
            },
            {
              type: 'category',
              label: 'Rancher-Managed Clusters',
              link: {
                type: 'doc',
                id: "rancher-managed-clusters",
              },
              items: [
                     "tutorials/best-practices/rancher-managed-clusters/logging-best-practices",
                     "tutorials/best-practices/rancher-managed-clusters/monitoring-best-practices",
                     "tutorials/best-practices/rancher-managed-clusters/tips-to-set-up-containers",
                     "tutorials/best-practices/rancher-managed-clusters/rancher-managed-clusters-in-vsphere"
                     ]
            }
                ]
        },
        {
          type: 'category',
          label: 'Kubernetes Cluster Setup',
          link: {
            type: 'doc',
            id: "kubernetes-cluster-setup",
                },
          items: [
                  "tutorials/kubernetes-cluster-setup/high-availability-installs",
                  "tutorials/kubernetes-cluster-setup/k3s-for-rancher",
                  "tutorials/kubernetes-cluster-setup/rke1-for-rancher",
                  "tutorials/kubernetes-cluster-setup/rke2-for-rancher",
                  ],
        },
        {
          type: 'category',
          label: 'Infrastructure Setup',
          link: {
            type: 'doc',
            id: "infrastructure-setup",
          },
          items: [
                  "tutorials/infrastructure-setup/ha-k3s-kubernetes-cluster",
                  "tutorials/infrastructure-setup/ha-rke1-kubernetes-cluster",
                  "tutorials/infrastructure-setup/ha-rke2-kubernetes-cluster",
                  "tutorials/infrastructure-setup/nodes-in-amazon-ec2",
                  "tutorials/infrastructure-setup/mysql-database-in-amazon-rds",
                  "tutorials/infrastructure-setup/nginx-load-balancer",
                  "tutorials/infrastructure-setup/amazon-elb-load-balancer",
                  ],
        },
        {
          type: 'category',
          label: 'Kubernetes Clusters in Rancher Setup',
          link: {
            type: 'doc',
            id: "kubernetes-clusters-in-rancher-setup",
          },
          items: [
                  "tutorials/kubernetes-clusters-in-rancher-setup/node-requirements-for-rancher-managed-clusters",
            {
              type: 'category',
              label: 'Checklist for Production-Ready Clusters',
               link: {
                 type: 'doc',
                 id: "checklist-for-production-ready-clusters",
                  },
                items: [
                   "tutorials/kubernetes-clusters-in-rancher-setup/checklist-for-production-ready-clusters/recommended-cluster-architecture",
                   "tutorials/kubernetes-clusters-in-rancher-setup/checklist-for-production-ready-clusters/roles-for-nodes-in-kubernetes",
                         ],
            },
            {      
              type: 'category',
              label: 'Set Up Clusters from Hosted Kubernetes Providers',
              link: {
                type: 'doc',
                id: "set-up-clusters-from-hosted-kubernetes-providers",
                  },
                items: [
                     "tutorials/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/gke",
                     "tutorials/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/aks",
                     "tutorials/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/alibaba",
                     "tutorials/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/tencent",
                     "tutorials/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/huawei",
                       ]
            },
            { 
              type: 'category',
              label: 'Launch Kubernetes with Rancher',
              link: {
                type: 'doc',
                id: "launch-kubernetes-with-rancher",
                  },
              items: [
                 {
                    type: 'category',
                    label: 'Use New Nodes in an Infra Provider',
                    link: {
                      type: 'doc',
                       id: "use-new-nodes-in-an-infra-provider",
                        },
                        items: [
                            {
                              type: 'category',
                              label: 'vSphere',
                              link: {
                                type: 'doc',
                                id: "vsphere",
                              },
                              items: [
                                "tutorials/kubernetes-clusters-in-rancher-setup/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/vsphere/provision-kubernetes-clusters-in-vsphere",
                                "tutorials/kubernetes-clusters-in-rancher-setup/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/vsphere/create-credentials",     
                                      ]
                            },
                            {
                              type: 'category',
                              label: 'Nutanix',
                              link: {
                                type: 'doc',
                                id: "nutanix",
                              },
                              items: [
                                "tutorials/kubernetes-clusters-in-rancher-setup/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/nutanix/provision-kubernetes-clusters-in-aos",          
                                     ]
                              }
                        ]
                  },
                  {
                     type: 'category',
                     label: 'Use Windows Clusters',
                     link: {
                       type: 'doc',
                       id: "use-windows-clusters",
                        },
                        items: [
                           "tutorials/kubernetes-clusters-in-rancher-setup/launch-kubernetes-with-rancher/use-windows-clusters/azure-storageclass-configuration",
                           "tutorials/kubernetes-clusters-in-rancher-setup/launch-kubernetes-with-rancher/use-windows-clusters/windows-linux-cluster-feature-parity",
                           "tutorials/kubernetes-clusters-in-rancher-setup/launch-kubernetes-with-rancher/use-windows-clusters/network-requirements-for-host-gateway",
                               ]
                  },
                  {
                     type: 'category',
                     label: 'Set Up Cloud Providers',
                     link: {
                       type: 'doc',
                       id: "set-up-cloud-providers",
                        },
                        items: [
                            {
                              type: 'category',
                              label: 'Other Cloud Providers',
                              items: [
                                "tutorials/kubernetes-clusters-in-rancher-setup/launch-kubernetes-with-rancher/set-up-cloud-providers/other-cloud-providers/amazon",
                                "tutorials/kubernetes-clusters-in-rancher-setup/launch-kubernetes-with-rancher/set-up-cloud-providers/other-cloud-providers/azure",
                                "tutorials/kubernetes-clusters-in-rancher-setup/launch-kubernetes-with-rancher/set-up-cloud-providers/other-cloud-providers/google-compute-engine",
                                    ]
                            },
                            {
                              type: 'category',
                              label: 'vSphere',
                              link: {
                                type: 'doc',
                                id: "vsphere-cloud-provider"
                              },
                              items: [
                                "tutorials/kubernetes-clusters-in-rancher-setup/launch-kubernetes-with-rancher/set-up-cloud-providers/vsphere/configure-in-tree-vsphere",
                                "tutorials/kubernetes-clusters-in-rancher-setup/launch-kubernetes-with-rancher/set-up-cloud-providers/vsphere/configure-out-of-tree-vsphere",
                                "tutorials/kubernetes-clusters-in-rancher-setup/launch-kubernetes-with-rancher/set-up-cloud-providers/vsphere/migrate-from-in-tree-to-out-of-tree",
                                    ]
                                }
                             ]
                  },                   
                     "tutorials/kubernetes-clusters-in-rancher-setup/launch-kubernetes-with-rancher/rke1-vs-rke2-differences",
                      
                     "tutorials/kubernetes-clusters-in-rancher-setup/launch-kubernetes-with-rancher/about-rancher-agents",
                        ]
            },
              "tutorials/kubernetes-clusters-in-rancher-setup/register-existing-clusters", 
            ]
        },
        {
          type: 'category',
          label: 'Kubernetes Resources Setup',
          link: {
            type: 'doc',
            id: "kubernetes-resources-setup",
          },
          items: [
            {
              type: 'category',
              label: 'Workloads and Pods',
              link: {
                type: 'doc',
                id: "workloads-and-pods",
              },
              items: [
                     "tutorials/kubernetes-resources-setup/workloads-and-pods/deploy-workloads",
                     "tutorials/kubernetes-resources-setup/workloads-and-pods/roll-back-workloads",
                     "tutorials/kubernetes-resources-setup/workloads-and-pods/upgrade-workloads",
                     "tutorials/kubernetes-resources-setup/workloads-and-pods/add-a-sidecar",                            
                     ]
            },
            {
              type: 'category',
              label: 'Horizontal Pod Autoscaler',
              link: {
                type: 'doc',
                id: "horizontal-pod-autoscaler",
              },
              items: [
                     "tutorials/kubernetes-resources-setup/horizontal-pod-autoscaler/about-hpas",
                     "tutorials/kubernetes-resources-setup/horizontal-pod-autoscaler/manage-hpas-with-ui",
                     "tutorials/kubernetes-resources-setup/horizontal-pod-autoscaler/manage-hpas-with-kubectl",
                     "tutorials/kubernetes-resources-setup/horizontal-pod-autoscaler/test-hpas-with-kubectl",                            
                     ]
                    },
            {
              type: 'category',
              label: 'Load Balancer and Ingress Controller',
              link: {
                type: 'doc',
                id: "load-balancer-and-ingress-controller",
              },
              items: [
                     "tutorials/kubernetes-resources-setup/load-balancer-and-ingress-controller/layer-4-and-layer-7-load-balancing",
                     "tutorials/kubernetes-resources-setup/load-balancer-and-ingress-controller/add-ingresses",
                     "tutorials/kubernetes-resources-setup/load-balancer-and-ingress-controller/configure-ingresses",                           
                     ]
            },                  
                     "tutorials/kubernetes-resources-setup/create-services", 
           
                     "tutorials/kubernetes-resources-setup/encrypt-http-communication", 
            
                     "tutorials/kubernetes-resources-setup/configmaps", 
             
                     "tutorials/kubernetes-resources-setup/secrets", 
             
                     "tutorials/kubernetes-resources-setup/kubernetes-and-docker-registries", 
                     ],
        },
        {
          type: 'category',
          label: 'Helm Charts in Rancher',
          link: {
            type: 'doc',
            id: "helm-charts-in-rancher",
          },
          items: [
                 "tutorials/helm-charts-in-rancher/create-apps",                            
                     ]
        },
        {
          type: 'category',
          label: 'Deploy Apps Across Clusters',
          link: {
            type: 'doc',
            id: "deploy-apps-across-clusters",
          },
          items: [
                 "tutorials/deploy-apps-across-clusters/fleet",
                 "tutorials/deploy-apps-across-clusters/multi-cluster-apps",                            
                     ]
        },
        {
          type: 'category',
          label: 'Backup, Restore, and Disaster Recovery',
          link: {
            type: 'doc',
            id: "backup-restore-and-disaster-recovery",
          },
          items: [
            "tutorials/backup-restore-and-disaster-recovery/back-up-rancher",
            "tutorials/backup-restore-and-disaster-recovery/restore-rancher",
            "tutorials/backup-restore-and-disaster-recovery/migrate-rancher-to-new-cluster",
            "tutorials/backup-restore-and-disaster-recovery/back-up-docker-installed-rancher",
            "tutorials/backup-restore-and-disaster-recovery/restore-docker-installed-rancher",
            "tutorials/backup-restore-and-disaster-recovery/back-up-rancher-launched-kubernetes-clusters",
            "tutorials/backup-restore-and-disaster-recovery/restore-rancher-launched-kubernetes-clusters-from-backup",                            
                ]
              }
            ]
    },  
    {
      type: 'category',
      label: 'How-to Guides',
      link: {
        type: 'doc',
        id: "how-to-guides",
      },
      items: [ 
        {
          type: 'category',
          label: 'Authentication, Permissions, and Global Configuration',
          items: [
            {
              type: 'category',
              label: 'About Authentication',
              items: [
                {
                  type: 'category',
                  label: 'Authentication Config',
                  items: [
                         "how-to-guides/authentication-permissions-and-global-configuration/about-authentication/authentication-config/manage-users-and-groups",
                         "how-to-guides/authentication-permissions-and-global-configuration/about-authentication/authentication-config/create-local-users",
                         "how-to-guides/authentication-permissions-and-global-configuration/about-authentication/authentication-config/configure-google-oauth",
                         "how-to-guides/authentication-permissions-and-global-configuration/about-authentication/authentication-config/configure-active-directory",
                         "how-to-guides/authentication-permissions-and-global-configuration/about-authentication/authentication-config/configure-freeipa",
                         "how-to-guides/authentication-permissions-and-global-configuration/about-authentication/authentication-config/configure-azure-ad",
                         "how-to-guides/authentication-permissions-and-global-configuration/about-authentication/authentication-config/configure-github",
                         "how-to-guides/authentication-permissions-and-global-configuration/about-authentication/authentication-config/configure-keycloak-oidc",
                         "how-to-guides/authentication-permissions-and-global-configuration/about-authentication/authentication-config/configure-keycloak-saml",
                         "how-to-guides/authentication-permissions-and-global-configuration/about-authentication/authentication-config/configure-pingidentity",
                         "how-to-guides/authentication-permissions-and-global-configuration/about-authentication/authentication-config/configure-okta-saml",
                     ]
                },
                {
                  type: 'category',
                  label: 'Configure Microsoft AD Federation Service (SAML)',
                  items: [
                         "how-to-guides/authentication-permissions-and-global-configuration/about-authentication/configure-microsoft-ad-federation-service-saml/configure-ms-adfs-for-rancher",
                         "how-to-guides/authentication-permissions-and-global-configuration/about-authentication/configure-microsoft-ad-federation-service-saml/configure-rancher-for-ms-adfs",
                         ]
                },
                {
                  type: 'category',
                  label: 'Configure Shibboleth (SAML)',
                  items: [
                         "how-to-guides/authentication-permissions-and-global-configuration/about-authentication/configure-shibboleth-saml/about-group-permissions",
                         ]
                        }
                      ]
            },
            {
              type: 'category',
              label: 'Manage Role-Based Access Control (RBAC)',
              items: [
                     "how-to-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/global-permissions",
                     "how-to-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/cluster-and-project-roles",
                     "how-to-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/custom-roles",
                     "how-to-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/locked-roles",
                     ]
            },
            {
              type: 'category',
              label: 'About Provisioning Drivers',
              items: [
                     "how-to-guides/authentication-permissions-and-global-configuration/about-provisioning-drivers/manage-cluster-drivers",
                     "how-to-guides/authentication-permissions-and-global-configuration/about-provisioning-drivers/manage-node-drivers",
                     ]
            },
            {
              type: 'category',
              label: 'About RKE1 Templates',
              items: [
                     "how-to-guides/authentication-permissions-and-global-configuration/about-rke1-templates/create-permissions",
                     "how-to-guides/authentication-permissions-and-global-configuration/about-rke1-templates/access-or-share-templates",
                     "how-to-guides/authentication-permissions-and-global-configuration/about-rke1-templates/manage-rke1-templates",
                     "how-to-guides/authentication-permissions-and-global-configuration/about-rke1-templates/enforce-templates",
                     "how-to-guides/authentication-permissions-and-global-configuration/about-rke1-templates/override-template-settings",
                     "how-to-guides/authentication-permissions-and-global-configuration/about-rke1-templates/apply-templates",
                     "how-to-guides/authentication-permissions-and-global-configuration/about-rke1-templates/infrastructure",
                     "how-to-guides/authentication-permissions-and-global-configuration/about-rke1-templates/example-use-cases",
                     ]
            },
            {
              type: 'category',
              label: 'Manage Cluster Templates',
              items: [
                     "how-to-guides/authentication-permissions-and-global-configuration/manage-cluster-templates/cluster-templates",
                  ]
            },
            {
              type: 'category',
              label: 'Create Pod Security Policies',
              items: [
                     "how-to-guides/authentication-permissions-and-global-configuration/create-pod-security-policies/create-psp",
                  ]
            },
            {
              type: 'category',
              label: 'Configure a Global Default Private Registry',
              items: [
                     "how-to-guides/authentication-permissions-and-global-configuration/configure-a-global-default-private-registry/global-default-private-registry",
                  ]
            },
            {
              type: 'category',
              label: 'Set Up Custom Branding',
              items: [
                     "how-to-guides/authentication-permissions-and-global-configuration/set-up-custom-branding/custom-branding",
                  ]
                }
              ]
        },
        {
          type: 'category',
          label: 'Manage Clusters',
          items: [
            {
              type: 'category',
              label: 'Access Clusters',
              items: [
                     "how-to-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig",
                     "how-to-guides/manage-clusters/access-clusters/authorized-cluster-endpoint",
                     "how-to-guides/manage-clusters/access-clusters/add-users-to-clusters",
                     ] 
            },
            {
              type: 'category',
              label: 'Install Cluster Autoscaler',
              items: [
                     "how-to-guides/manage-clusters/install-cluster-autoscaler/use-aws-ec2-auto-scaling-groups",
                     ]
            },
            {
              type: 'category',
              label: 'Create Kubernetes Persistent Storage',
              items: [
                  {
                    type: 'category',
                    label: 'Manage Persistent Storage',
                    items: [
                     "how-to-guides/manage-clusters/create-kubernetes-persistent-storage/manage-persistent-storage/about-persistent-storage",
                     "how-to-guides/manage-clusters/create-kubernetes-persistent-storage/manage-persistent-storage/set-up-existing-storage",
                     "how-to-guides/manage-clusters/create-kubernetes-persistent-storage/manage-persistent-storage/dynamically-provision-new-storage",
                     "how-to-guides/manage-clusters/create-kubernetes-persistent-storage/manage-persistent-storage/use-external-ceph-driver",
                     "how-to-guides/manage-clusters/create-kubernetes-persistent-storage/manage-persistent-storage/about-glusterfs-volumes",
                     "how-to-guides/manage-clusters/create-kubernetes-persistent-storage/manage-persistent-storage/install-iscsi-volumes", 
                     ]
                  },
                  {
                    type: 'category',
                    label: 'Provisioning Storage Examples',
                    items: [
                      "how-to-guides/manage-clusters/create-kubernetes-persistent-storage/provisioning-storage-examples/persistent-storage-in-amazon-ebs",
                      "how-to-guides/manage-clusters/create-kubernetes-persistent-storage/provisioning-storage-examples/nfs-storage",
                      "how-to-guides/manage-clusters/create-kubernetes-persistent-storage/provisioning-storage-examples/vsphere-storage",
                           ]
                          }
                        ]
            },
            {
              type: 'category',
              label: 'About Projects and Namespaces',
              items: [
                "how-to-guides/manage-clusters/about-projects-and-namespaces/projects-and-namespaces",
                     ]   
            },
            {
              type: 'category',
              label: 'Clone Cluster Configuration',
              items: [
                "how-to-guides/manage-clusters/clone-cluster-configuration/clone-cluster-config",
                     ]
            },
            {
              type: 'category',
              label: 'Rotate Certificates',
              items: [
                "how-to-guides/manage-clusters/rotate-certificates/rotate-certificates",
                     ]
            },
            {
              type: 'category',
              label: 'Manage Nodes and Node Pools',
              items: [
                "how-to-guides/manage-clusters/manage-nodes-and-node-pools/nodes-and-node-pools",
                     ]
            },
            {
              type: 'category',
              label: 'Clean Cluster Nodes',
              items: [
                "how-to-guides/manage-clusters/clean-cluster-nodes/clean-cluster-nodes", 
                     ]
            },
            {
              type: 'category',
              label: 'Add a Pod Security Policy',
              items: [
                "how-to-guides/manage-clusters/add-a-pod-security-policy/add-psp", 
                     ]
            },
            {
              type: 'category',
              label: 'Assign Pod Security Policies',
              items: [
                "how-to-guides/manage-clusters/assign-pod-security-policies/assign-psp", 
                     ]
                   }
                  ]
        },
        {
          type: 'category',
          label: 'Manage Projects',
          items: [
            {
              type: 'category',
              label: 'Add Users to Projects',
              items: [
                  "how-to-guides/manage-projects/add-users-to-projects/add-users-to-projects",
                     ]
            },
            {
              type: 'category',
              label: 'Manage Namespaces',
              items: [
                 "how-to-guides/manage-projects/manage-namespaces/manage-namespaces",
                     ]
            },
            {
              type: 'category',
              label: 'About CI/CD Pipelines',
              items: [
                 "how-to-guides/manage-projects/about-ci-cd-pipelines/ci-cd-pipelines",
                     ]
            },
            {
              type: 'category',
              label: 'Manage Pod Security Policies',
              items: [
                 "how-to-guides/manage-projects/manage-pod-security-policies/manage-psp",
                     ]
            },
            {
              type: 'category',
              label: 'Manage Project Resource Quotas',
              items: [
                 "how-to-guides/manage-projects/manage-project-resource-quotas/about-project-resource-quotas",
                 "how-to-guides/manage-projects/manage-project-resource-quotas/override-default-limit-in-namespaces",
                 "how-to-guides/manage-projects/manage-project-resource-quotas/set-container-default-resource-limits",
                 "how-to-guides/manage-projects/manage-project-resource-quotas/resource-quota-types",
                     ]
                    }
                  ]
        },
        {
          type: 'category',
          label: 'Monitoring/Alerting Guides',
          items: [
             "how-to-guides/monitoring-alerting-guides/enable-monitoring",
             "how-to-guides/monitoring-alerting-guides/uninstall-monitoring", 
             "how-to-guides/monitoring-alerting-guides/set-up-monitoring-for-workloads",
             "how-to-guides/monitoring-alerting-guides/customize-grafana-dashboard",
             "how-to-guides/monitoring-alerting-guides/create-persistent-grafana-dashboard",
             "how-to-guides/monitoring-alerting-guides/debug-high-memory-usage",
             "how-to-guides/monitoring-alerting-guides/migrate-to-rancher-v2.5+-monitoring", 
                     ]
        },
        {
          type: 'category',
          label: 'Monitoring V2 Configuration',
          items: [
            {
              type: 'category',
              label: 'Advanced Configuration',
              items: [
                 "how-to-guides/monitoring-v2-configuration/advanced-configuration/alertmanager",
                 "how-to-guides/monitoring-v2-configuration/advanced-configuration/prometheus",
                 "how-to-guides/monitoring-v2-configuration/advanced-configuration/prometheusrules",
                     ]
                    }
                  ]
        },
        {
          type: 'category',
          label: 'Istio Setup Guide',
          items: [
             "how-to-guides/istio-setup-guide/enable-istio-in-cluster",
             "how-to-guides/istio-setup-guide/enable-istio-in-namespace",
             "how-to-guides/istio-setup-guide/use-istio-sidecar",
             "how-to-guides/istio-setup-guide/set-up-istio-gateway",
             "how-to-guides/istio-setup-guide/set-up-traffic-management",
             "how-to-guides/istio-setup-guide/generate-and-view-traffic",
          ]
        },
        {
          type: 'category',
          label: 'CIS Scan Guides',
          items: [
             "how-to-guides/cis-scan-guides/install-rancher-cis-benchmark",
             "how-to-guides/cis-scan-guides/uninstall-rancher-cis-benchmark",
             "how-to-guides/cis-scan-guides/run-a-scan",
             "how-to-guides/cis-scan-guides/run-a-scan-periodically-on-a-schedule",
             "how-to-guides/cis-scan-guides/skip-tests",
             "how-to-guides/cis-scan-guides/view-reports",
             "how-to-guides/cis-scan-guides/enable-alerting-for-rancher-cis-benchmark",
             "how-to-guides/cis-scan-guides/configure-alerts-for-periodic-scan-on-a-schedule",
             "how-to-guides/cis-scan-guides/create-a-custom-benchmark-version-to-run",
                  ],
                }
              ]
            },
    {
      type: 'category',
      label: 'Reference Guides',
      items: [ 
        {
          type: 'category',
          label: 'Architecture',
          items: [
            {
              type: 'category',
              label: 'Rancher Manager Architecture',
              items: [
                 "reference-guides/architecture/rancher-manager-architecture/rancher-server-and-components",
                 "reference-guides/architecture/rancher-manager-architecture/communicating-with-downstream-user-clusters",
                    ]
              },
                 "reference-guides/architecture/architecture-recommendations",
                       ]
        },
        {
          type: 'category',
          label: 'Cluster Configuration',
          items: [
            {
              type: 'category',
              label: 'Rancher Server',
              items: [
                "reference-guides/cluster-configuration/rancher-server/rke1-cluster-configuration",
                "reference-guides/cluster-configuration/rancher-server/rke2-cluster-configuration",
                "reference-guides/cluster-configuration/rancher-server/k3s-cluster-configuration",
                "reference-guides/cluster-configuration/rancher-server/eks-cluster-configuration",
                "reference-guides/cluster-configuration/rancher-server/aks-cluster-configuration",
                {
                  type: 'category',
                  label: 'GKE',
                  items: [
                    "reference-guides/cluster-configuration/rancher-server/gke/gke-private-clusters",
                  ]
                },
                {
                  type: 'category',
                  label: 'Use Existing Nodes',
                  items: [
                    "reference-guides/cluster-configuration/rancher-server/use-existing-nodes/rancher-agent-options",
                   ]
          },
                "reference-guides/cluster-configuration/rancher-server/sync-clusters",
                      ]
                  },
            {
              type: 'category',
              label: 'Downstream Clusters',
              items: [
                {
                  type: 'category',
                  label: 'Node Template Configuration',
                  items: [ 
                    "reference-guides/cluster-configuration/downstream-clusters/node-template-configuration/amazon-ec2",
                    "reference-guides/cluster-configuration/downstream-clusters/node-template-configuration/digitalocean",
                    "reference-guides/cluster-configuration/downstream-clusters/node-template-configuration/azure", 
                    "reference-guides/cluster-configuration/downstream-clusters/node-template-configuration/vsphere",
                    "reference-guides/cluster-configuration/downstream-clusters/node-template-configuration/nutanix",
                          ]
                },
                {
                  type: 'category',
                  label: 'Machine Configuration',
                  items: [ 
                    "reference-guides/cluster-configuration/downstream-clusters/machine-configuration/amazon-ec2",
                    "reference-guides/cluster-configuration/downstream-clusters/machine-configuration/digitalocean",
                    "reference-guides/cluster-configuration/downstream-clusters/machine-configuration/azure", 
                         ]
                        }
                      ]
                    }
                  ]
                },
        {
          type: 'category',
          label: 'Single-Node Rancher in Docker',
          items: [
           "reference-guides/single-node-rancher-in-docker/http-proxy-configuration",
           "reference-guides/single-node-rancher-in-docker/advanced-options",
                 ]
        },
        {
          type: 'category',
          label: 'Installation References',
          items: [
           "reference-guides/installation-references/helm-chart-options",
           "reference-guides/installation-references/tls-settings",
           "reference-guides/installation-references/feature-flags"
                 ]
        },
        {
          type: 'category',
          label: 'Permissions',
          items: [
            {
              type: 'category',
              label: 'Amazon EKS', 
              items: [
                "reference-guides/permissions/amazon-eks/minimum-eks-permissions",
                    ]
                  }
                ]
        },               
        {
          type: 'category',
          label: 'Backup & Restore Configuration',
          items: [
                 "reference-guides/backup-restore-configuration/backup-configuration",
                 "reference-guides/backup-restore-configuration/restore-configuration",
                 "reference-guides/backup-restore-configuration/storage-configuration", 
                 ],
        },
        {
          type: 'category',
          label: 'Configure OpenLDAP',
          items: [
                "reference-guides/configure-openldap/openldap-config-reference",
                    ]
        },               
        {
          type: 'category',
          label: 'Kubernetes Concepts',
          items: [
            "reference-guides/kubernetes-concepts/overview-of-kubernetes-components",
                   ],
        },
        {
          type: 'category',
          label: 'Monitoring V2 Configuration',
          items: [
            "reference-guides/monitoring-v2-configuration/receivers",
            "reference-guides/monitoring-v2-configuration/routes",
            "reference-guides/monitoring-v2-configuration/servicemonitors-and-podmonitors",
            "reference-guides/monitoring-v2-configuration/helm-chart-options",
            "reference-guides/monitoring-v2-configuration/examples",
                   ],
        },
        {
          type: 'category',
          label: 'User Settings',
          items: [
            "reference-guides/user-settings/api-keys",
            "reference-guides/user-settings/manage-node-templates",
            "reference-guides/user-settings/manage-cloud-credentials",
            "reference-guides/user-settings/user-preferences",
                 ],
        },
        {
          type: 'category',
          label: 'CLI with Rancher',
          items: [
            "reference-guides/cli-with-rancher/rancher-cli",
            "reference-guides/cli-with-rancher/kubectl-utility",
                 ]
        },
        {
          type: 'category',
          label: 'About the API',
          items: [
            "reference-guides/about-the-api/api-tokens",
                 ]
        },
        {
          type: 'category',
          label: 'Rancher Cluster Tools',
          items: [
            "reference-guides/rancher-cluster-tools/cluster-logging-monitoring-and-visibility-tools",
                 ],
        },
        {
          type: 'category',
          label: 'Rancher Project Tools',
          items: [
            "reference-guides/rancher-project-tools/project-logging-monitoring-and-visibility-tools",     
                 ],         
        },
            "reference-guides/system-tools", 

            "reference-guides/rke1-template-example-yaml",     
        {
          type: 'category',
          label: 'Pipelines',
          items: [
            "reference-guides/pipelines/concepts",
            "reference-guides/pipelines/pipeline-configuration",
            "reference-guides/pipelines/configure-persistent-data",
            "reference-guides/pipelines/example-repositories",
            "reference-guides/pipelines/example-yaml",
                 ],
        },
        {
          type: 'category',
          label: 'Rancher Security',
          items: [
            {
              type: 'category',
              label: 'Rancher v2.6 Hardening Guides',
              items: [
                "reference-guides/rancher-security/rancher-v2.6-hardening-guides/hardening-guide-with-cis-v1.6-benchmark",
                "reference-guides/rancher-security/rancher-v2.6-hardening-guides/self-assessment-guide-with-cis-v1.6-benchmark",
                 ],
            },
            {  
              type: 'category',
              label: 'SELinux RPM',
              items: [
                "reference-guides/rancher-security/selinux-rpm/about-rancher-selinux",
                "reference-guides/rancher-security/selinux-rpm/about-rke2-selinux",
                     ],
            },
            {
              type: 'category',
              label: 'Kubernetes Security Best Practices',
              items: [
                "reference-guides/rancher-security/kubernetes-security-best-practices/kubernetes-security",
                     ],
            },
            {
              type: 'category',
              label: 'Security Advisories and CVEs',
              items: [
                "reference-guides/rancher-security/security-advisories-and-cves/published-advisories-and-cves",
                     ]
                   }
                  ],
                }
              ]
            },
    {    
      type: 'category',
      label: 'Explanations', 
      items: [
        "explanations/sample",
                           ],
    },                                                       
    {
      type: 'category',
      label: 'Integrations in Rancher',
      items: [ 
        {
          type: 'category',
          label: 'CIS Scans',
          items: [
            "integrations-in-rancher/cis-scans/configuration-reference",
            "integrations-in-rancher/cis-scans/rbac-for-cis-scans",
            "integrations-in-rancher/cis-scans/skipped-and-not-applicable-tests",
            "integrations-in-rancher/cis-scans/custom-benchmark",
                 ],
        },
        {
          type: 'category',
          label: 'Fleet',
          items: [
            "integrations-in-rancher/fleet/gitops-at-scale",
            "integrations-in-rancher/fleet/architecture",
            "integrations-in-rancher/fleet/windows-support",
            "integrations-in-rancher/fleet/use-fleet-behind-a-proxy",
                 ]
        },
        {
          type: 'category',
          label: 'Harvester',
          items: [
            "integrations-in-rancher/harvester/about-harvester",
                 ]
        },
        {
          type: 'category',
          label: 'Istio',
          items: [ 
            {
              type: 'category',
              label: 'About Istio',
              items: [
                "integrations-in-rancher/istio/about-istio/cpu-and-memory-allocations",
                "integrations-in-rancher/istio/about-istio/rbac-for-istio",
                "integrations-in-rancher/istio/about-istio/disable-istio",
                     ]
            },
            {
              type: 'category',
              label: 'Configuration Options',
              items: [
                "integrations-in-rancher/istio/configuration-options/pod-security-policies",
                "integrations-in-rancher/istio/configuration-options/selectors-and-scrape-configurations",
                "integrations-in-rancher/istio/configuration-options/install-istio-on-rke2-cluster",
                "integrations-in-rancher/istio/configuration-options/project-network-isolation",
                     ]
                   }
                 ]
        },
        {
          type: 'category',
          label: 'Longhorn',
          items: [
            "integrations-in-rancher/longhorn/about-longhorn-storage",
                 ]
        },
        {
          type: 'category',
          label: 'Logging',
          items: [ 
            {
              type: 'category',
              label: 'About Logging',
              items: [
                "integrations-in-rancher/logging/about-logging/logging-architecture",
                "integrations-in-rancher/logging/about-logging/migrate-to-rancher-v2.5+-logging",
                "integrations-in-rancher/logging/about-logging/rbac-for-logging",
                "integrations-in-rancher/logging/about-logging/logging-helm-chart-options",
                "integrations-in-rancher/logging/about-logging/taints-and-tolerations",
                     ]
            },
            {
              type: 'category',
              label: 'Custom Resource Configuration',
              items: [
                "integrations-in-rancher/logging/custom-resource-configuration/flows-and-clusterflows",
                "integrations-in-rancher/logging/custom-resource-configuration/outputs-and-clusteroutputs"
                     ]
                    }
                  ]
        },
        {
          type: 'category',
          label: 'Monitoring and Alerting',
          items: [
            "integrations-in-rancher/monitoring-and-alerting/how-monitoring-works",
            "integrations-in-rancher/monitoring-and-alerting/rbac-for-monitoring",
            "integrations-in-rancher/monitoring-and-alerting/built-in-dashboards",
            "integrations-in-rancher/monitoring-and-alerting/windows-support",
            "integrations-in-rancher/monitoring-and-alerting/promql-expressions",
            "integrations-in-rancher/monitoring-and-alerting/prometheus-federator",
                 ]
        },
        {
          type: 'category',
          label: 'NeuVector',
          items: [
            "integrations-in-rancher/neuvector/about-neuvector",
                 ]
        },
        {
          type: 'category',
          label: 'OPA Gatekeeper',
          items: [
            "integrations-in-rancher/opa-gatekeeper/about-opa-gatekeeper",
          ],
        }
      ]
    },
    {
      type: 'category',
      label: 'FAQ',
      items: [
        "faq/deprecated-features-in-v2.5",
        "faq/install-and-configure-kubectl",
        "faq/dockershim",
        "faq/technical-items",
        "faq/security",
        "faq/telemetry",
        "faq/container-network-interface-providers",
        "faq/rancher-is-no-longer-needed",
      ],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      items: [ 
        {
          type: 'category',
          label: 'Kubernetes Components',
          items: [
            "troubleshooting/kubernetes-components/troubleshooting-etcd-nodes",
            "troubleshooting/kubernetes-components/troubleshooting-controlplane-nodes",
            "troubleshooting/kubernetes-components/troubleshooting-nginx-proxy",
            "troubleshooting/kubernetes-components/troubleshooting-worker-nodes-and-generic-components",
                 ]
        },
        {
          type: 'category',
          label: 'Other Troubleshooting Tips',
          items: [
            "troubleshooting/other-troubleshooting-tips/kubernetes-resources",
            "troubleshooting/other-troubleshooting-tips/networking",
            "troubleshooting/other-troubleshooting-tips/dns",
            "troubleshooting/other-troubleshooting-tips/rancher-ha",
            "troubleshooting/other-troubleshooting-tips/registered-clusters",
            "troubleshooting/other-troubleshooting-tips/logging",
            "troubleshooting/other-troubleshooting-tips/user-id-tracking-in-audit-logs",
            "troubleshooting/other-troubleshooting-tips/expired-webhook-certificate-rotation",
                 ],
                }
              ]
    },
    {
      type: 'category',
      label: 'Contribute to Rancher',
      items: [
        "contribute-to-rancher/contribute-to-rancher",
      ]
    } 
  ],
}
module.exports = sidebars;
